### ISSUE TITLE
some sort of repeat syntax 

### ISSUE THREAD

**Issue by jsnkuhn** [Datyedyeguy/rando-tracker#2]
Would like to bring something like the repeat="" syntax over from the desktop tracker to cover things like the Zelda 1 and 4 maps.

I'm picturing the html to look something like:
`<img src="map.gif" data-repeat="128"/>`

Would be best if this were part of a global js.

**Comment by Datyedyeguy** [comment]
This is now implemented.  You can set data-repeat="#" on an element and it will copy said element that many times.  What is also does is set the data-index attribute uniquely for each element, starting at 0, so you can identify them within any code.  Currently in action in the Z1R 2-player layout.
