### ISSUE TITLE
Tracker/commentator view

### ISSUE THREAD

**Issue by jsnkuhn** [Datyedyeguy/rando-tracker#4]
Need some sort of tracker view. and possibly commentator view?

This should be a global thing. Pretty straight forward i think. Just `display:none` all the things that aren't tracker or name.

**Comment by Datyedyeguy** [comment]
This is done with a separate html file, named {layout}_tracker.html.  This way we can be sure to optimize layout space.  Same JS file can be used to minimize rework.
