### ISSUE TITLE
easier dismissing of tracker popup menu

### ISSUE THREAD

**Issue by jsnkuhn** [Datyedyeguy/rando-tracker#5]
The "multi state tracker popup menu" (tm) that opens when you click an icon that has more than 2 states should be dismissed if you click else where on the layout. Right now it requires you to interact with it by clicking on an icon to close even if you don't want to change the icon state (ie accidentally clicked the wrong icon).  

I'm wondering if the same should go for the settings panel....

**Comment by Datyedyeguy** [comment]
Dialogs are now handled by the tracker library and are closed when anything is clicked.
