### ISSUE TITLE
attributes for column-count and tracker icon sizes

### ISSUE THREAD

**Issue by jsnkuhn** [Datyedyeguy/rando-tracker#8]
capt_uhu - Today at 10:23 AM

holy cow, so many github changes :-). Just one thing i noticed: don't know if you know but css grid has a repeat syntax: https://developer.mozilla.org/en-US/docs/Web/CSS/repeat. This puts in my mind of the possibility for something similar to the xSize="42", ySize="42",  xNumber="3" we had on the desktop app. Maybe optional data-columns="16", data-icon-size="", data-icon-width="", data-icon-height="" ?

**Comment by jsnkuhn** [comment]
occurs to me that if we are doing `data-column` then we might as well do `data-row`. Then this could optionally be used for both all layout and tracking icons.

**Comment by Datyedyeguy** [comment]
The xSize and ySize could easily be done with CSS rules.  And yeah, data-column and data-row for the css grid should take care of the rest of that.  The current z1r/two.html uses grid-template-columns to control it, but it's really open to whatever folks are comfortable with.

With all that said, I don't think anything extra needs to be added to the tracker.js to allow for this unless I'm missing something.

**Comment by jsnkuhn** [comment]
I guess my original thinking was to optionally make it possible to parallel the way we did the grids in the desktop tracker by writing out the # of columns an attribute in the tags.... You're right though, probably not really necessary.
